(function(){window.WPD="undefined"!==typeof window.WPD?window.WPD:{};if("undefined"!=typeof WPD.dom)return!1;WPD.dom=function(){if("undefined"==typeof WPD.dom.fn||"undefined"==typeof WPD.dom.fn.a)WPD.dom.fn={a:[],is_wpd_dom:!0,length:0,get:function(c){return"undefined"==typeof c?this.a.slice():"undefined"!=typeof this.a[c]?this.a[c]:null},_:function(c){return"<"===c.charAt(0)?WPD.dom._fn.createElementsFromHTML(c):Array.prototype.slice.call(document.querySelectorAll(c))},$:function(c,b){let a=this.copy(this,
!0);a.a="undefined"!=typeof b?null!==b?b.find(c).get():[]:"string"==typeof c?a._(c):null!==c?[c]:[];a.length=a.a.length;return a},extend:function(){for(let c=1;c<arguments.length;c++)for(let b in arguments[c])arguments[c].hasOwnProperty(b)&&(arguments[0][b]=arguments[c][b]);return arguments[0]},copy:function(c,b){let a,d,e;if("object"!=typeof c||null===c)return c;a=new c.constructor;for(d in c)c.hasOwnProperty(d)&&(e=typeof c[d],a[d]=b&&"object"===e&&null!==c[d]?this.copy(c[d]):c[d]);return a},parent:function(c){let b=
this.get(0),a=this.copy(this,!0);a.a=[];null!=b&&(b=b.parentElement,"undefined"!=typeof c?b.matches(c)&&(a.a=[b]):a.a=null==b?[]:[b]);return a},first:function(){let c=this.copy(this,!0);c.a="undefined"!=typeof c.a[0]?[c.a[0]]:[];c.length=c.a.length;return c},last:function(){let c=this.copy(this,!0);c.a=0<c.a.length?[c.a[c.a.length-1]]:[];c.length=c.a.length;return c},prev:function(c){let b=this.copy(this,!0);if("undefined"==typeof c)b.a="undefined"!=typeof b.a[0]&&null!=b.a[0].previousElementSibling?
[b.a[0].previousElementSibling]:[];else if("undefined"!=typeof b.a[0]){let a=b.a[0].previousElementSibling;for(b.a=[];null!=a;){if(a.matches(c)){b.a=[a];break}a=a.previousElementSibling}}b.length=b.a.length;return b},next:function(c){let b=this.copy(this,!0);if("undefined"==typeof c)b.a="undefined"!=typeof b.a[0]&&null!=b.a[0].nextElementSibling?[b.a[0].nextElementSibling]:[];else if("undefined"!=typeof b.a[0]){let a=b.a[0].nextElementSibling;for(b.a=[];null!=a;){if(a.matches(c)){b.a=[a];break}a=
a.nextElementSibling}}b.length=b.a.length;return b},closest:function(c){let b=this.get(0),a=this.copy(this,!0);a.a=[];if("string"===typeof c){if(null!==b&&"undefined"!=typeof b.matches&&""!==c){if(!b.matches(c))for(;(b=b.parentElement)&&!b.matches(c););a.a=null==b?[]:[b]}}else if(null!==b&&"undefined"!=typeof b.matches&&"undefined"!=typeof c.matches){if(b!==c)for(;(b=b.parentElement)&&b!==c;);a.a=null==b?[]:[b]}a.length=a.a.length;return a},add:function(c){if("undefined"!==typeof c)if("undefined"!==
typeof c.nodeType)-1==this.a.indexOf(c)&&this.a.push(c);else if("undefined"!==typeof c.a){let b=this;c.a.forEach(function(a){-1==b.a.indexOf(a)&&b.a.push(a)})}return this},find:function(c){let b=this.copy(this,!0);b.a=[];this.forEach(function(a){null!==a&&"undefined"!=typeof a.querySelectorAll&&(b.a=b.a.concat(Array.prototype.slice.call(a.querySelectorAll(c))))});b.length=b.a.length;return b},forEach:function(c){this.a.forEach(function(b,a,d){c.apply(b,[b,a,d])});return this},each:function(c){return this.forEach(c)},
hasClass:function(c){let b=this.get(0);return null!=b?b.classList.contains(c):!1},addClass:function(c){let b=c;"string"==typeof c&&(b=c.split(" "));b=b.filter(function(a){return""!==a.trim()});0<b.length&&this.forEach(function(a){a.classList.add.apply(a.classList,b)});return this},removeClass:function(c){if("undefined"!=typeof c){let b=c;"string"==typeof c&&(b=c.split(" "));b=b.filter(function(a){return""!==a.trim()});0<b.length&&this.forEach(function(a){a.classList.remove.apply(a.classList,b)})}else this.forEach(function(b){0<
b.classList.length&&b.classList.remove.apply(b.classList,b.classList)});return this},is:function(c){let b=this.get(0);return null!=b?b.matches(c):!1},val:function(c){let b=this.get(0);if(null!=b)if(1==arguments.length)if("select-multiple"==b.type){c="string"===typeof c?c.split(","):c;for(let a=0,d=b.options.length,e;a<d;a++)e=b.options[a],e.selected=-1!=c.indexOf(e.value)}else b.value=c;else return"select-multiple"==b.type?Array.prototype.map.call(b.selectedOptions,function(a){return a.value}):b.value;
return this},isVisible:function(){let c=this.get(0),b=!0,a;for(;null!==c;){a=window.getComputedStyle(c);if("none"==a.display||"hidden"==a.visibility||0==a.opacity){b=!1;break}c=c.parentElement}return b},attr:function(c,b){let a,d=arguments,e=this;this.forEach(function(f){2==d.length?(f.setAttribute(c,b),a=e):"object"===typeof c?Object.keys(c).forEach(function(g){f.setAttribute(g,c[g])}):a=f.getAttribute(c)});return a},removeAttr:function(c){this.forEach(function(b){b.removeAttribute(c)});return this},
prop:function(c,b){let a,d=arguments;this.forEach(function(e){2==d.length?e[c]=b:a="undefined"!=typeof e[c]?e[c]:null});return 2==d.length?this:a},data:function(c,b){let a=this.get(0),d=c.replace(/-([a-z])/g,function(e){return e[1].toUpperCase()});return null!=a?2==arguments.length?(a.dataset[d]=b,this):"undefined"==typeof a.dataset[d]?"":a.dataset[d]:""},html:function(c){let b=this.get(0);return null!=b?1==arguments.length?(b.innerHTML=c,this):b.innerHTML:""},text:function(c){let b=this.get(0);return null!=
b?1==arguments.length?(b.textContent=c,this):b.textContent:""},css:function(c,b){let a=this.get(),d;for(let e=0;e<a.length;e++)if(d=a[e],1==arguments.length)if("object"==typeof c)Object.keys(c).forEach(function(f){d.style[f]=c[f]});else return window.getComputedStyle(d)[c];else d.style[c]=b;return this},position:function(){let c=this.get(0);return null!=c?{top:c.offsetTop,left:c.offsetLeft}:{top:0,left:0}},offset:function(){let c=this.get(0);return null!=c?WPD.dom._fn.hasFixedParent(c)?c.getBoundingClientRect():
WPD.dom._fn.absolutePosition(c):{top:0,left:0}},outerWidth:function(c){c=c||!1;let b=this.get(0);if(null!=b)return c?parseInt(b.offsetWidth)+parseInt(this.css("marginLeft"))+parseInt(this.css("marginRight")):parseInt(b.offsetWidth)},outerHeight:function(c){return c?parseInt(this.css("height"))+parseInt(this.css("marginTop"))+parseInt(this.css("marginBottom")):parseInt(this.css("height"))},innerWidth:function(){var c=this.get(0);return null!=c?(c=window.getComputedStyle(c),this.outerWidth()-parseFloat(c.borderLeftWidth)-
parseFloat(c.borderRightWidth)):0},width:function(){return this.outerWidth()},height:function(){return this.outerHeight()},on:function(){let c=arguments,b=function(d,e){let f;if("mouseenter"==e.type||"mouseleave"==e.type||"hover"==e.type){var g=document.elementFromPoint(e.clientX,e.clientY);if(!g.matches(d[1]))for(;(g=g.parentElement)&&!g.matches(d[1]););null!=g&&(f=WPD.dom(g))}else f=WPD.dom(e.target).closest(d[1]);if(null!=f&&0<f.closest(this).length){g=[];g.push(e);if("undefined"!=typeof d[4])for(e=
4;e<d.length;e++)g.push(d[e]);d[2].apply(f.get(0),g)}},a=c[0].split(" ");for(let d=0;d<a.length;d++){let e=a[d];if("string"==typeof c[1])this.forEach(function(f){if(!WPD.dom._fn.hasEventListener(f,e,c[2])){let g=b.bind(f,c);f.addEventListener(e,g,c[3]);f._wpd_el="undefined"==typeof f._wpd_el?[]:f._wpd_el;f._wpd_el.push({type:e,selector:c[1],func:g,trigger:c[2],args:c[3]})}});else for(let f=0;f<a.length;f++){let g=a[f];this.forEach(function(h){WPD.dom._fn.hasEventListener(h,g,c[1])||(h.addEventListener(g,
c[1],c[2]),h._wpd_el="undefined"==typeof h._wpd_el?[]:h._wpd_el,h._wpd_el.push({type:g,func:c[1],trigger:c[1],args:c[2]}))})}}return this},off:function(c,b){this.forEach(function(a){if("undefined"!=typeof a._wpd_el&&0<a._wpd_el.length)if("undefined"===typeof c){let d;for(;d=a._wpd_el.pop();)a.removeEventListener(d.type,d.func,d.args);a._wpd_el=[]}else c.split(" ").forEach(function(d){if("undefined"==typeof b){let e;for(;e=a._wpd_el.pop();)a.removeEventListener(d,e.func,e.args);a._wpd_el=[]}else{let e=
[];a._wpd_el.forEach(function(f){f.type==d&&f.trigger==b?a.removeEventListener(d,f.func,f.args):e.push(f)});a._wpd_el=e}})});return this},offForced:function(){let c=this;this.forEach(function(b,a){let d=b.cloneNode(!0);b.parentNode.replaceChild(d,b);c.a[a]=d});return this},trigger:function(c,b,a,d){a=a||!1;d=d||!1;this.forEach(function(e){var f=!1;d&&"undefined"!=typeof jQuery&&"undefined"!=typeof jQuery._data&&"undefined"!=typeof jQuery._data(e,"events")&&"undefined"!=typeof jQuery._data(e,"events")[c]&&
(jQuery(e).trigger(c,b),f=!0);!f&&a&&(f=new Event(c),f.detail=b,e.dispatchEvent(f));if("undefined"!=typeof e._wpd_el)e._wpd_el.forEach(function(g){if(g.type==c){let h=new Event(c);g.trigger.apply(e,[h].concat(b))}});else{let g=!1,h=e;for(;;){h=h.parentElement;if(null==h)break;"undefined"!=typeof h._wpd_el&&h._wpd_el.forEach(function(k){if("undefined"!==typeof k.selector){var l=WPD.dom(h).find(k.selector);0<l.length&&0<=l.get().indexOf(e)&&k.type==c&&(l=new Event(c),k.trigger.apply(e,[l].concat(b)),
g=!0)}});if(g)break}}});return this},clone:function(){let c=this.get(0);null!=c?(this.a=[c.cloneNode(!0)],this.length=this.a.length):this.a=[];this.length=this.a.length;return this},remove:function(c){if("undefined"!=typeof c)return c.parentElement.removeChild(c);this.forEach(function(b){if(null!=b.parentElement)return b.parentElement.removeChild(b)});this.a=[];this.length=this.a.length;return null},detach:function(){let c=this,b=[];this.forEach(function(a){a=c.remove(a);null!=a&&b.push(a)});this.a=
b;this.length=this.a.length;return this},prepend:function(c){"string"==typeof c&&(c=WPD.dom._fn.createElementsFromHTML(c));c=Array.isArray(c)?c:[c];this.forEach(function(b){c.forEach(function(a){"undefined"!=typeof a.is_wpd_dom?a.forEach(function(d){b.insertBefore(d,b.children[0])}):b.insertBefore(a,b.children[0])})});return this},append:function(c){"string"==typeof c&&(c=WPD.dom._fn.createElementsFromHTML(c));c=Array.isArray(c)?c:[c];this.forEach(function(b){c.forEach(function(a){null!=a&&("undefined"!=
typeof a.is_wpd_dom?a.forEach(function(d){b.appendChild(d)}):b.appendChild(a.cloneNode(!0)))})});return this},uuidv4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){let b=16*Math.random()|0;return("x"==c?b:b&3|8).toString(16)})}},WPD.dom._fn={bodyTransform:function(){let c=0,b=0;if("undefined"!==typeof WebKitCSSMatrix){var a=window.getComputedStyle(document.body);"undefined"!=typeof a.transform&&(a=new WebKitCSSMatrix(a.transform),"undefined"!=a.m41&&(c=a.m41),
"undefined"!=a.m42&&(b=a.m42))}return{x:c,y:b}},bodyTransformY:function(){return this.bodyTransform().y},bodyTransformX:function(){return this.bodyTransform().x},hasFixedParent:function(c){if(0!=WPD.dom._fn.bodyTransformY())return!1;do if("fixed"==window.getComputedStyle(c).position)return!0;while(c=c.parentElement);return!1},hasEventListener:function(c,b,a){if("undefined"==typeof c._wpd_el)return!1;for(let d=0;d<c._wpd_el.length;d++)if(c._wpd_el[d].trigger==a&&c._wpd_el[d].type==b)return!0;return!1},
allDescendants:function(c){let b=[],a=this;Array.isArray(c)||(c=[c]);c.forEach(function(d){for(let e=0;e<d.childNodes.length;e++){let f=d.childNodes[e];b.push(f);b=b.concat(a.allDescendants(f))}});return b},createElementsFromHTML:function(c){let b=document.createElement("template");b.innerHTML=c.replace(/(\r\n|\n|\r)/gm,"");return Array.prototype.slice.call(b.content.childNodes)},absolutePosition:function(c){if(!c.getClientRects().length)return{top:0,left:0};let b=c.getBoundingClientRect();c=c.ownerDocument.defaultView;
return{top:b.top+c.pageYOffset,left:b.left+c.pageXOffset}},plugin:function(c,b){WPD.dom.fn[c]=function(a){return"undefined"!=typeof a&&b[a]?b[a].apply(this,Array.prototype.slice.call(arguments,1)):this.each(function(d){d["wpd_dom_"+c]=Object.create(b).init(a,d)})}}},WPD.dom.version=1;return 1<=arguments.length?WPD.dom.fn.$.apply(WPD.dom.fn,arguments):WPD.dom.fn};WPD.dom();document.dispatchEvent(new Event("wpd-dom-core-loaded"))})();
(function(){if("undefined"!=typeof WPD.dom.fn.animate)return!1;WPD.dom.fn._animate={easing:{linear:function(c){return c},easeInOutQuad:function(c){return.5>c?2*c*c:1-Math.pow(-2*c+2,2)/2},easeOutQuad:function(c){return 1-(1-c)*(1-c)}}};WPD.dom.fn.animate=function(c,b,a){let d=this;b=b||200;a=a||"linear";this.forEach(function(e){let f,g=0,h,k={},l={},m,p,q;m=d.prop("_wpd_dom_animations");m=null==m?[]:m;!1===c?m.forEach(function(n){clearInterval(n)}):(q="undefined"!=typeof d._animate.easing[a]?d._animate.easing[a]:
d._animate.easing.easeInOutQuad,Object.keys(c).forEach(function(n){-1<n.indexOf("scroll")?k[n]=e[n]:k[n]=parseInt(window.getComputedStyle(e)[n]);l[n]=c[n]-k[n]}),f=b/1E3*60,p=setInterval(function(){g++;g>f?clearInterval(p):(h=q(g/f),Object.keys(l).forEach(function(n){-1<n.indexOf("scroll")?e[n]=k[n]+l[n]*h:e.style[n]=k[n]+l[n]*h+"px"}))},1E3/60),m.push(p),d.prop("_wpd_dom_animations",m))});return this};document.dispatchEvent(new Event("wpd-dom-animate-loaded"))})();
(function(){let c=WPD.dom;if("undefined"!=typeof WPD.dom.fn.unhighlight)return!1;WPD.dom.fn.unhighlight=function(b){let a={className:"highlight",element:"span"};c.fn.extend(a,b);return this.find(a.element+"."+a.className).each(function(){let d=this.parentNode;d.replaceChild(this.firstChild,this);d.normalize()})};WPD.dom.fn.highlight=function(b,a){function d(g,h,k,l,m){m=""==m?".exhghttt":m;if(3===g.nodeType){if(h=g.data.normalize("NFD").replace(/[\u0300-\u036f]/g,"").match(h))return k=document.createElement(k||
"span"),k.className=l||"highlight",l=/\.|,|\s/.test(h[0].charAt(0))?h.index+1:h.index,g=g.splitText(l),g.splitText(h[1].length),l=g.cloneNode(!0),k.appendChild(l),g.parentNode.replaceChild(k,g),1}else if(1===g.nodeType&&g.childNodes&&!/(script|style)/i.test(g.tagName)&&0< !c(g).closest(m).length&&(g.tagName!==k.toUpperCase()||g.className!==l))for(let p=0;p<g.childNodes.length;p++)p+=d(g.childNodes[p],h,k,l,m);return 0}let e={className:"highlight",element:"span",caseSensitive:!1,wordsOnly:!1,excludeParents:""};
c.fn.extend(e,a);b.constructor===String&&(b=[b]);b=b.filter(function(g){return""!=g});b.forEach(function(g,h,k){k[h]=g.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&").normalize("NFD").replace(/[\u0300-\u036f]/g,"")});if(0==b.length)return this;a=e.caseSensitive?"":"i";b="("+b.join("|")+")";e.wordsOnly&&(b="(?:,|^|\\s)"+b+"(?:,|$|\\s)");let f=new RegExp(b,a);return this.each(function(g){d(g,f,e.element,e.className,e.excludeParents)})}})();
(function(){if("undefined"!=typeof WPD.dom.fn.serialize)return!1;WPD.dom.fn.serialize=function(){let c=this.get(0);if(c&&"FORM"===c.nodeName){var b,a,d=[];for(b=c.elements.length-1;0<=b;--b)if(""!==c.elements[b].name)switch(c.elements[b].nodeName){case "INPUT":switch(c.elements[b].type){case "text":case "hidden":case "password":case "button":case "reset":case "submit":d.push(c.elements[b].name+"="+encodeURIComponent(c.elements[b].value));break;case "checkbox":case "radio":c.elements[b].checked&&d.push(c.elements[b].name+
"="+encodeURIComponent(c.elements[b].value))}break;case "TEXTAREA":d.push(c.elements[b].name+"="+encodeURIComponent(c.elements[b].value));break;case "SELECT":switch(c.elements[b].type){case "select-one":d.push(c.elements[b].name+"="+encodeURIComponent(c.elements[b].value));break;case "select-multiple":for(a=c.elements[b].options.length-1;0<=a;--a)c.elements[b].options[a].selected&&d.push(c.elements[b].name+"="+encodeURIComponent(c.elements[b].options[a].value))}break;case "BUTTON":switch(c.elements[b].type){case "reset":case "submit":case "button":d.push(c.elements[b].name+
"="+encodeURIComponent(c.elements[b].value))}}return d.join("&")}};WPD.dom.fn.serializeForAjax=function(c,b){let a=[],d;for(d in c)if(c.hasOwnProperty(d)){let e=b?b+"["+d+"]":d,f=c[d];a.push(null!==f&&"object"===typeof f?WPD.dom.fn.serializeForAjax(f,e):encodeURIComponent(e)+"="+encodeURIComponent(f))}return a.join("&")};document.dispatchEvent(new Event("wpd-dom-serialize-loaded"))})();
(function(){if("undefined"!=typeof WPD.dom.fn.inViewPort)return!1;WPD.dom.fn.inViewPort=function(c,b){var a=this.get(0);let d;if(null==a)return!1;c="undefined"==typeof c?0:c;b="undefined"==typeof b?window:"string"==typeof b?document.querySelector(b):b;var e=a.getBoundingClientRect();a=e.top;let f=e.bottom,g=e.left,h=e.right;null==b&&(b=window);b===window?(e=window.innerWidth||0,d=window.innerHeight||0):(e=b.clientWidth,d=b.clientHeight,b=b.getBoundingClientRect(),a-=b.top,f-=b.top,g-=b.left,h-=b.left);
c=~~Math.round(parseFloat(c));return 0>=h||g>=e?!1:0<c?a>=c&&f<d-c:(0<f&&a<=d-c)|(0>=a&&f>c)};document.dispatchEvent(new Event("wpd-dom-viewport-loaded"))})();
(function(){if("undefined"!=typeof WPD.dom.fn.ajax)return!1;WPD.dom.fn.ajax=function(c){c=this.extend({url:"",method:"GET",cors:"cors",data:{},success:null,fail:null,accept:"text/html",contentType:"application/x-www-form-urlencoded; charset=UTF-8"},c);if("cors"!=c.cors){var b="ajax_cb_"+this.uuidv4().replaceAll("-","");WPD.dom.fn[b]=function(){c.success.apply(this,arguments);delete WPD.dom.fn[c.data.fn]};c.data.callback="WPD.dom.fn."+b;c.data.fn=b;b=document.createElement("script");b.type="text/javascript";
b.src=c.url+"?"+this.serializeForAjax(c.data);b.onload=function(){this.remove()};document.body.appendChild(b)}else return b=new XMLHttpRequest,b.onreadystatechange=function(){null!=c.success&&4==this.readyState&&200==this.status&&c.success(this.responseText);null!=c.fail&&4==this.readyState&&400<=this.status&&c.fail(this)},b.open(c.method.toUpperCase(),c.url,!0),b.setRequestHeader("Content-type",c.contentType),b.setRequestHeader("Accept",c.accept),b.send(this.serializeForAjax(c.data)),b};document.dispatchEvent(new Event("wpd-dom-xhttp-loaded"))})();
window.WPD=window.WPD||{};
window.WPD.Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(c){let b="";let a,d,e,f,g,h=0;for(c=this._utf8_encode(c);h<c.length;){var k=c.charCodeAt(h++);a=c.charCodeAt(h++);d=c.charCodeAt(h++);e=k>>2;k=(k&3)<<4|a>>4;f=(a&15)<<2|d>>6;g=d&63;isNaN(a)?f=g=64:isNaN(d)&&(g=64);b=b+this._keyStr.charAt(e)+this._keyStr.charAt(k)+this._keyStr.charAt(f)+this._keyStr.charAt(g)}return b},decode:function(c){let b="";let a,d,e,f=0;for(c=c.replace(/[^A-Za-z0-9\+\/=]/g,
"");f<c.length;){var g=this._keyStr.indexOf(c.charAt(f++));var h=this._keyStr.indexOf(c.charAt(f++));d=this._keyStr.indexOf(c.charAt(f++));e=this._keyStr.indexOf(c.charAt(f++));g=g<<2|h>>4;h=(h&15)<<4|d>>2;a=(d&3)<<6|e;b+=String.fromCharCode(g);64!=d&&(b+=String.fromCharCode(h));64!=e&&(b+=String.fromCharCode(a))}return b=this._utf8_decode(b)},_utf8_encode:function(c){c=c.replace(/\r\n/g,"\n");let b="";for(let a=0;a<c.length;a++){let d=c.charCodeAt(a);128>d?b+=String.fromCharCode(d):(127<d&&2048>
d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(c){let b="",a=0,d,e,f;for(;a<c.length;)d=c.charCodeAt(a),128>d?(b+=String.fromCharCode(d),a++):191<d&&224>d?(e=c.charCodeAt(a+1),b+=String.fromCharCode((d&31)<<6|e&63),a+=2):(e=c.charCodeAt(a+1),f=c.charCodeAt(a+2),b+=String.fromCharCode((d&15)<<12|(e&63)<<6|f&63),a+=3);return b}};
(function(){window.WPD=window.WPD||{};WPD.Hooks=WPD.Hooks||{};let c=WPD.Hooks;c.filters=c.filters||{};c.addFilter=function(b,a,d,e){c.filters[b]=c.filters[b]||[];c.filters[b].push({priority:"undefined"===typeof d?10:d,scope:"undefined"===typeof e?null:e,callback:a})};c.removeFilter=function(b,a){"undefined"!=typeof c.filters[b]&&("undefined"==typeof a?c.filters[b]=[]:c.filters[b].forEach(function(d,e){d.callback===a&&c.filters[b].splice(e,1)}))};c.applyFilters=function(b){let a=[],d=Array.prototype.slice.call(arguments),
e=arguments[1];"undefined"!==typeof c.filters[b]&&0<c.filters[b].length&&(c.filters[b].forEach(function(f){a[f.priority]=a[f.priority]||[];a[f.priority].push({scope:f.scope,callback:f.callback})}),d.splice(0,2),a.forEach(function(f){f.forEach(function(g){e=g.callback.apply(g.scope,[e].concat(d))})}));return e}})();window.WPD=window.WPD||{};
window.WPD.intervalUntilExecute=function(c,b,a,d){let e,f=0,g="function"===typeof b?b():b;a="undefined"==typeof a?100:a;d="undefined"==typeof d?50:d;if(!1===g)e=setInterval(function(){g="function"===typeof b?b():b;f++;if(f>d)return clearInterval(e),!1;if(!1!==g)return clearInterval(e),c(g)},a);else return c(g)};
(function(){window.WPD="undefined"!==typeof window.WPD?window.WPD:{};window.WPD.ajaxsearchlite=new function(){this.prevState=null;this.firstIteration=!0;this.helpers={};this.plugin={};this.addons={addons:[],add:function(c){-1==this.addons.indexOf(c)&&(c=this.addons.push(c),this.addons[c-1].init())},remove:function(c){this.addons.filter(function(b){return b.name==c?("undefined"!=typeof b.destroy&&b.destroy(),!1):!0})}}}})();WPD.dom._fn.plugin("ajaxsearchlite",window.WPD.ajaxsearchlite.plugin);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{autocompleteGoogleOnly:function(){let b=this,a=b.n("text").val();if(""==b.n("text").val())b.n("textAutocomplete").val("");else{var d=b.n("textAutocomplete").val();if(""==d||0!=d.indexOf(a)){b.n("textAutocomplete").val("");var e=b.o.autocomplete.lang;["wpml_lang","polylang_lang","qtranslate_lang"].forEach(function(f){0<c('input[name="'+f+'"]',b.n("searchsettings")).length&&1<c('input[name="'+f+'"]',b.n("searchsettings")).val().length&&(e=c('input[name="'+
f+'"]',b.n("searchsettings")).val())});b.n("text").val().length>=b.o.autocomplete.trigger_charcount&&c.fn.ajax({url:"https://clients1.google.com/complete/search",cors:"no-cors",data:{q:a,hl:e,nolabels:"t",client:"hp",ds:""},success:function(f){0<f[1].length&&(f=f[1][0][0].replace(/(<([^>]+)>)/ig,""),f=c("<textarea />").html(f).text(),f=f.substr(a.length),b.n("textAutocomplete").val(a+f),b.fixAutocompleteScrollLeft())}})}}},fixAutocompleteScrollLeft:function(){this.n("textAutocomplete").get(0).scrollLeft=
this.n("text").get(0).scrollLeft}})})(WPD.dom);(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{setFilterStateInput:function(a){let d=this;"undefined"==typeof a&&(a=65);let e=function(){JSON.stringify(d.originalFormData)!=JSON.stringify(b.formData(c("form",d.n("searchsettings"))))?d.n("searchsettings").find("input[name=filters_initial]").val(0):d.n("searchsettings").find("input[name=filters_initial]").val(1)};0==a?e():setTimeout(function(){e()},a)}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{gaPageview:function(b){let a=this.gaGetTrackingID();if("undefined"==typeof ASL.analytics||"pageview"!=ASL.analytics.method)return!1;if(""!=ASL.analytics.string){let d="function"==typeof __gaTracker?__gaTracker:"function"==typeof ga?ga:!1,e="function"==typeof gtag?gtag:!1;window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:""));let f=this.o.homeurl.replace(window.location.origin,
"");if(!1!==e)!1!==a&&a.forEach(function(g){e("config",g,{page_path:f+ASL.analytics.string.replace("{asl_term}",b)})});else if(!1!==d){let g={page:f+ASL.analytics.string.replace("{asl_term}",b),title:"Ajax Search"};!1!==a?a.forEach(function(h){d("create",h,"auto");d("send","pageview",g)}):d("send","pageview",g)}}},gaEvent:function(b,a){let d=this.gaGetTrackingID();if("undefined"==typeof ASL.analytics||"event"!=ASL.analytics.method)return!1;let e="function"==typeof gtag?gtag:!1,f="function"==typeof window.__gaTracker?
window.__gaTracker:"function"==typeof window.ga?window.ga:!1;if(!1===e&&!1===f&&"undefined"==typeof window.dataLayer)return!1;if("undefined"!=typeof ASL.analytics.event[b]&&1==ASL.analytics.event[b].active){let g={search_id:this.o.id,search_name:this.o.name,phrase:this.n("text").val(),option_name:"",option_value:"",result_title:"",result_url:"",results_count:""},h={event_category:ASL.analytics.event[b].category,event_label:ASL.analytics.event[b].label,value:ASL.analytics.event[b].value};a=c.fn.extend(g,
a);Object.keys(a).forEach(function(k){let l=a[k];l=String(l).replace(/[\s\n\r]+/g," ").trim();Object.keys(h).forEach(function(m){h[m]=h[m].replace(new RegExp("{"+k+"}","gmi"),l)})});!1!==f?!1!==d?d.forEach(function(k){f("create",k,"auto");f("send","event",h.event_category,ASL.analytics.event[b].action,h.event_label,h.value)}):f("send","event",h.event_category,ASL.analytics.event[b].action,h.event_label,h.value):!1!==e?!1!==d?d.forEach(function(k){h.send_to=k;e("event",ASL.analytics.event[b].action,
h)}):e("event",ASL.analytics.event[b].action,h):"undefined"!=typeof window.dataLayer.push&&window.dataLayer.push({event:"gaEvent",eventCategory:h.event_category,eventAction:ASL.analytics.event[b].action,eventLabel:h.event_label})}},gaGetTrackingID:function(){if("undefined"==typeof ASL.analytics)return!1;if("undefined"!=typeof ASL.analytics.tracking_id&&""!=ASL.analytics.tracking_id)return[ASL.analytics.tracking_id];if(!1===("function"==typeof window.gtag?window.gtag:!1)&&"undefined"!=typeof window.ga&&
"undefined"!=typeof window.ga.getAll){let b=[];window.ga.getAll().forEach(function(a){b.push(a.get("trackingId"))});return 0<b.length?b:!1}return!1}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{liveLoad:function(a,d,e,f){function g(m){m=b.Hooks.applyFilters("asl/live_load/raw_data",m,l);var p=new DOMParser;let q=p.parseFromString(m,"text/html"),n=c(q);l.o.statistics&&l.stat_addKeyword(l.o.id,l.n("text").val());if(""!=m&&0<n.length&&0<n.find(a).length){m=m.replace(/&asl_force_reset_pagination=1/gmi,"");m=m.replace(/%26asl_force_reset_pagination%3D1/gmi,"");m=m.replace(/&#038;asl_force_reset_pagination=1/gmi,
"");b.isSafari()&&(m=m.replace(/srcset/gmi,"nosrcset"));m=b.Hooks.applyFilters("asl/live_load/html",m,l.o.id,l.o.iid);m=b.wp_hooks_apply_filters("asl/live_load/html",m,l.o.id,l.o.iid);n=c(p.parseFromString(m,"text/html"));p=n.find(a).get(0);p=b.Hooks.applyFilters("asl/live_load/replacement_node",p,l,k.get(0),m);null!=p&&k.get(0).parentNode.replaceChild(p,k.get(0));k=c(a).first();e&&(document.title=q.title,history.pushState({},null,d));c(a).first().find(".woocommerce-ordering").on("change","select.orderby",
function(){c(this).closest("form").trigger("submit")});if(1==l.o.singleHighlight)c(a).find("a").on("click",function(){localStorage.removeItem("asl_phrase_highlight");""!=b.unqoutePhrase(l.n("text").val())&&localStorage.setItem("asl_phrase_highlight",JSON.stringify({phrase:b.unqoutePhrase(l.n("text").val())}))});b.Hooks.applyFilters("asl/live_load/finished",d,l,a,k.get(0));ASL.initialize();l.lastSuccesfulSearch=c("form",l.n("searchsettings")).serialize()+l.n("text").val().trim();l.lastSearchData=m}l.n("s").trigger("asl_search_end",
[l.o.id,l.o.iid,l.n("text").val(),m],!0,!0);let r,t;null==(t=(r=l).gaEvent)||t.call(r,"search_end",{results_count:"unknown"});let u,v;null==(v=(u=l).gaPageview)||v.call(u,l.n("text").val());l.hideLoader();k.css("opacity",1);l.searching=!1;""!=l.n("text").val()&&l.n("proclose").css({display:"block"})}if("body"==a||"html"==a)return console.log("Ajax Search Pro: Do not use html or body as the live loader selector."),!1;""==ASL.pageHTML&&"undefined"===typeof ASL._ajax_page_html&&(ASL._ajax_page_html=
!0,c.fn.ajax({url:location.href,method:"GET",success:function(m){ASL.pageHTML=m},dataType:"html"}));e="undefined"==typeof e?!0:e;f="undefined"==typeof f?!1:f;let h=".search-content #content #Content div[role=main] main[role=main] div.theme-content div.td-ss-main-content main.l-content #primary".split(" ");"#main"!=a&&h.unshift("#main");if(1>c(a).length&&(h.forEach(function(m){if(0<c(m).length)return a=m,!1}),1>c(a).length))return console.log("Ajax Search Lite: The live search selector does not exist on the page."),
!1;a=b.Hooks.applyFilters("asl/live_load/selector",a,this);let k=c(a).first(),l=this;l.searchAbort();k.css("opacity",.4);b.Hooks.applyFilters("asl/live_load/start",d,l,a,k.get(0));f||1!=l.n("searchsettings").find("input[name=filters_initial]").val()||""!=l.n("text").val()?(l.searching=!0,l.post=c.fn.ajax({url:d,method:"GET",success:function(m){g(m)},dataType:"html",fail:function(m){k.css("opacity",1);m.aborted||(k.html("This request has failed. Please check your connection."),l.hideLoader(),l.searching=
!1,l.n("proclose").css({display:"block"}))}})):window.WPD.intervalUntilExecute(function(){g(ASL.pageHTML)},function(){return""!=ASL.pageHTML})},getCurrentLiveURL:function(){var a="asl_ls="+b.nicePhrase(this.n("text").val());let d="&",e=window.location.href;e=-1<e.indexOf("asl_ls=")?e.slice(0,e.indexOf("asl_ls=")):e;e=-1<e.indexOf("asl_ls&")?e.slice(0,e.indexOf("asl_ls&")):e;e=-1<e.indexOf("p_asid=")?e.slice(0,e.indexOf("p_asid=")):e;e=-1<e.indexOf("asl_")?e.slice(0,e.indexOf("asl_")):e;-1===e.indexOf("?")&&
(d="?");a=e+d+a+"&asl_active=1&asl_force_reset_pagination=1&p_asid="+this.o.id+"&p_asl_data=1&"+c("form",this.n("searchsettings")).serialize();return a=a.replace("?&","?")}})})(WPD.dom);(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showLoader:function(){this.n("proloading").css({display:"block"})},hideLoader:function(){this.n("proloading").css({display:"none"});this.n("results").css("display","")}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{loadASLFonts:function(){!1!==ASL.font_url&&((new FontFace("aslsicons2","url("+ASL.font_url+")",{style:"normal",weight:"normal","font-display":"swap"})).load().then(function(b){document.fonts.add(b)}).catch(function(b){}),ASL.font_url=!1)},updateHref:function(){if(this.o.trigger.update_href&&!this.usingLiveLoader){window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+
window.location.port:""));let b=this.getStateURL()+(this.resultsOpened?"&asl_s=":"&asl_ls=")+this.n("text").val();history.replaceState("","",b.replace(location.origin,""))}},fixClonedSelf:function(){let b=this.o.iid,a=this.o.rid;for(;!ASL.instances.set(this)&&!(++this.o.iid,50<this.o.iid););b!=this.o.iid&&(this.o.rid=this.o.id+"_"+this.o.iid,this.n("search").get(0).id="ajaxsearchlite"+this.o.rid,this.n("search").removeClass("asl_m_"+a).addClass("asl_m_"+this.o.rid).data("instance",this.o.iid),this.n("searchsettings").get(0).id=
this.n("searchsettings").get(0).id.replace("settings"+a,"settings"+this.o.rid),this.n("searchsettings").hasClass("asl_s_"+a)?this.n("searchsettings").removeClass("asl_s_"+a).addClass("asl_s_"+this.o.rid).data("instance",this.o.iid):this.n("searchsettings").removeClass("asl_sb_"+a).addClass("asl_sb_"+this.o.rid).data("instance",this.o.iid),this.n("resultsDiv").get(0).id=this.n("resultsDiv").get(0).id.replace("prores"+a,"prores"+this.o.rid),this.n("resultsDiv").removeClass("asl_r_"+a).addClass("asl_r_"+
this.o.rid).data("instance",this.o.iid),this.n("container").find(".asl_init_data").data("instance",this.o.iid),this.n("container").find(".asl_init_data").get(0).id=this.n("container").find(".asl_init_data").get(0).id.replace("asl_init_id_"+a,"asl_init_id_"+this.o.rid),this.n("prosettings").data("opened",0))},destroy:function(){let b=this;Object.keys(b.nodes).forEach(function(m){let p,q;null==(q=(p=b.nodes[m]).off)||q.call(p)});let a,d;null==(d=(a=b.n("searchsettings")).remove)||d.call(a);let e,f;
null==(f=(e=b.n("resultsDiv")).remove)||f.call(e);let g,h;null==(h=(g=b.n("search")).remove)||h.call(g);let k,l;null==(l=(k=b.n("container")).remove)||l.call(k);b.documentEventHandlers.forEach(function(m){c(m.node).off(m.event,m.handler)})}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{isRedirectToFirstResult:function(){return(0<c(".asl_res_url",this.n("resultsDiv")).length||0<c(".asl_es_"+this.o.id+" a").length||this.o.resPage.useAjax&&0<c(this.o.resPage.selector+"a").length)&&(1==this.o.redirectOnClick&&"click"==this.ktype&&"first_result"==this.o.trigger.click||1==this.o.redirectOnEnter&&("input"==this.ktype||"keyup"==this.ktype)&&13==this.keycode&&"first_result"==this.o.trigger.return)},
doRedirectToFirstResult:function(){let a,d;a="click"==this.ktype?this.o.trigger.click_location:this.o.trigger.return_location;0<c(".asl_res_url",this.n("resultsDiv")).length?d=c(c(".asl_res_url",this.n("resultsDiv")).get(0)).attr("href"):0<c(".asl_es_"+this.o.id+" a").length?d=c(c(".asl_es_"+this.o.id+" a").get(0)).attr("href"):this.o.resPage.useAjax&&0<c(this.o.resPage.selector+"a").length&&(d=c(c(this.o.resPage.selector+"a").get(0)).attr("href"));""!=d&&("same"==a?location.href=d:b.openInNewTab(d),
this.hideLoader(),this.hideResults());return!1},doRedirectToResults:function(a){let d;d="click"==a?this.o.trigger.click_location:this.o.trigger.return_location;a=this.getRedirectURL(a);if(this.o.overridewpdefault){if(1==this.o.resPage.useAjax)return this.hideResults(),this.liveLoad(this.o.resPage.selector,a),this.showLoader(),0==this.o.blocking&&this.hideSettings(),!1;"post"==this.o.override_method?b.submitToUrl(a,"post",{asl_active:1,p_asl_data:c("form",this.n("searchsettings")).serialize()},d):
"same"==d?location.href=a:b.openInNewTab(a)}else b.submitToUrl(a,"post",{np_asl_data:c("form",this.n("searchsettings")).serialize()},d);this.n("proloading").css("display","none");this.hideLoader();this.hideResults();this.searchAbort()},getRedirectURL:function(a){a="click"==("undefined"!==typeof a?a:"enter")?this.o.trigger.click:this.o.trigger.return;"results_page"==a||"ajax_search"==a?a="?s="+b.nicePhrase(this.n("text").val()):"woo_results_page"==a?a="?post_type=product&s="+b.nicePhrase(this.n("text").val()):
(a=this.o.trigger.redirect_url,a=a.replace(/{phrase}/g,b.nicePhrase(this.n("text").val())));1<this.o.homeurl.indexOf("?")&&0===a.indexOf("?")&&(a=a.replace("?","&"));if(this.o.overridewpdefault&&"post"!=this.o.override_method){let d="&";-1===this.o.homeurl.indexOf("?")&&-1===a.indexOf("?")&&(d="?");a=a+d+"asl_active=1&p_asl_data=1&"+c("form",this.n("searchsettings")).serialize();a=this.o.homeurl+a}else a=this.o.homeurl+a;a=a.replace("https://","https:///");a=a.replace("http://","http:///");a=a.replace(/\/\//g,
"/");a=b.Hooks.applyFilters("asl/redirect/url",a,this.o.id,this.o.iid);return a=b.wp_hooks_apply_filters("asl/redirect/url",a,this.o.id,this.o.iid)}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showResults:function(){this.initResults();this.createVerticalScroll();this.showVerticalResults();this.hideLoader();this.n("proclose").css({display:"block"});null!=this.n("showmore")&&(0<this.n("items").length?this.n("showmore").css({display:"block"}):this.n("showmore").css({display:"none"}));"undefined"!=typeof WPD.lazy&&setTimeout(function(){WPD.lazy(".asl_lazy")},100);this.resultsOpened=!0},hideResults:function(a){let d=
this;a="undefined"==typeof a?!0:a;if(!d.resultsOpened)return!1;d.n("resultsDiv").removeClass(d.resAnim.showClass).addClass(d.resAnim.hideClass);setTimeout(function(){d.n("resultsDiv").css(d.resAnim.hideCSS)},d.resAnim.duration);d.n("proclose").css({display:"none"});b.isMobile()&&a&&document.activeElement.blur();d.resultsOpened=!1;d.n("s").trigger("asl_results_hide",[d.o.id,d.o.iid],!0,!0)},showResultsBox:function(){this.n("s").trigger("asl_results_show",[this.o.id,this.o.iid],!0,!0);this.n("resultsDiv").css({display:"block",
height:"auto"});this.n("resultsDiv").css(this.resAnim.showCSS);this.n("resultsDiv").removeClass(this.resAnim.hideClass).addClass(this.resAnim.showClass);this.fixResultsPosition(!0)},scrollToResults:function(){var a=Math.floor(.1*window.innerHeight);if(this.resultsOpened&&1==this.o.scrollToResults.enabled&&!this.n("resultsDiv").inViewPort(a)){a="hover"==this.o.resultsposition?this.n("probox").offset().top-20:this.n("resultsDiv").offset().top-20;a+=this.o.scrollToResults.offset;var d=c("#wpadminbar");
0<d.length&&(a-=d.height());window.scrollTo({top:0>a?0:a,behavior:"smooth"})}}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showVerticalResults:function(){this.showResultsBox();if(0<this.n("items").length){let b=this.n("items").length<this.o.itemscount?this.n("items").length:this.o.itemscount;b=0>=b?9999:b;let a=c(".asl_group_header",this.n("resultsDiv"));if(0==this.o.itemscount||this.n("items").length<=this.o.itemscount)this.n("results").css({height:"auto"});else if(1>this.call_num&&this.n("results").css({height:"30px"}),1>this.call_num){let d=0,e=0,f=0,g=0;this.n("items").forEach(function(){e+=
c(this).outerHeight(!0);c(this).outerHeight(!0)>g&&(g=c(this).outerHeight(!0));d++});f=g*b;f>e&&(f=e);d=1>d?1:d;e=e/d*b;0<a.length&&a.forEach(function(h,k){h=Array.prototype.slice.call(h.parentNode.children).indexOf(h);h-k-Math.floor(h/3)<b&&(f+=c(this).outerHeight(!0))});this.n("results").css({height:f+"px"})}this.n("items").last().addClass("asl_last_item");this.n("results").find(".asl_group_header").prev(".item").addClass("asl_last_item");1==this.o.highlight&&c("div.item",this.n("resultsDiv")).highlight(this.n("text").val().split(" "),
{element:"span",className:"highlighted",wordsOnly:this.o.highlightWholewords})}this.resize();0==this.n("items").length&&this.n("results").css({height:"auto"});this.n("results").css({overflowY:"auto"});this.n("results").get(0).scrollTop=0;this.fixResultsPosition(!0);this.searching=!1}})})(WPD.dom);(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{createVerticalScroll:function(){}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{searchAbort:function(){null!=this.post&&this.post.abort()},searchWithCheck:function(a){let d=this;"undefined"==typeof a&&(a=50);d.n("text").val().length<d.o.charcount||(d.searchAbort(),clearTimeout(d.timeouts.searchWithCheck),d.timeouts.searchWithCheck=setTimeout(function(){d.search()},a))},search:function(){let a=this;if(!(a.n("text").val().length<a.o.charcount)){a.searching=!0;a.n("proloading").css({display:"block"});
a.n("proclose").css({display:"none"});var d={action:"ajaxsearchlite_search",aslp:a.n("text").val(),asid:a.o.id,options:c("form",a.n("searchsettings")).serialize()};d=b.Hooks.applyFilters("asl/search/data",d);d=b.wp_hooks_apply_filters("asl/search/data",d);if(JSON.stringify(d)===JSON.stringify(a.lastSearchData))return a.resultsOpened||a.showResults(),a.hideLoader(),a.isRedirectToFirstResult()&&a.doRedirectToFirstResult(),!1;var e;null==(e=a.gaEvent)||e.call(a,"search_start");0<c(".asl_es_"+a.o.id).length?
a.liveLoad(".asl_es_"+a.o.id,a.getCurrentLiveURL(),!1):a.o.resPage.useAjax?a.liveLoad(a.o.resPage.selector,a.getRedirectURL()):a.post=c.fn.ajax({url:ASL.ajaxurl,method:"POST",data:d,success:function(f){f=f.replace(/^\s*[\r\n]/gm,"");f=f.match(/___ASLSTART___(.*[\s\S]*)___ASLEND___/)[1];f=b.Hooks.applyFilters("asl/search/html",f);f=b.wp_hooks_apply_filters("asl/search/html",f);a.n("resdrg").html("");a.n("resdrg").html(f);c(".asl_keyword",a.n("resdrg")).on("click",function(){a.n("text").val(c(this).html());
c("input.orig",a.n("container")).val(c(this).html()).trigger("keydown");c("form",a.n("container")).trigger("submit","ajax");a.search()});a.nodes.items=c(".item",a.n("resultsDiv"));let g;null==(g=a.gaEvent)||g.call(a,"search_end",{results_count:a.n("items").length});let h;null==(h=a.gaPageview)||h.call(a,a.n("text").val());if(a.isRedirectToFirstResult())return a.doRedirectToFirstResult(),!1;a.hideLoader();a.showResults();a.scrollToResults();a.lastSuccesfulSearch=c("form",a.n("searchsettings")).serialize()+
a.n("text").val().trim();a.lastSearchData=d;a.updateHref();0==a.n("items").length?null!=a.n("showmore")&&a.n("showmore").css("display","none"):null!=a.n("showmore")&&(a.n("showmore").css("display","block"),c("span",a.n("showmore")).off(),c("span",a.n("showmore")).on("click",function(){var k=a.o.trigger.click;k="results_page"==k?"?s="+b.nicePhrase(a.n("text").val()):"woo_results_page"==k?"?post_type=product&s="+b.nicePhrase(a.n("text").val()):a.o.trigger.redirect_url.replace("{phrase}",b.nicePhrase(a.n("text").val()));
a.o.overridewpdefault?"post"==a.o.override_method?b.submitToUrl(a.o.homeurl+k,"post",{asl_active:1,p_asl_data:c("form",a.n("searchsettings")).serialize()}):location.href=a.o.homeurl+k+"&asl_active=1&p_asid="+a.o.id+"&p_asl_data=1&"+c("form",a.n("searchsettings")).serialize():b.submitToUrl(a.o.homeurl+k,"post",{np_asl_data:c("form",a.n("searchsettings")).serialize()})}))},fail:function(f){f.aborted||(a.n("resdrg").html(""),a.n("resdrg").html('<div class="asl_nores">The request failed. Please check your connection! Status: '+
f.status+"</div>"),a.nodes.items=c(".item",a.n("resultsDiv")),a.hideLoader(),a.showResults(),a.scrollToResults())}})}}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{showSettings:function(){let b;null==(b=this.initSettings)||b.call(this);this.n("searchsettings").css(this.settAnim.showCSS);this.n("searchsettings").removeClass(this.settAnim.hideClass).addClass(this.settAnim.showClass);this.n("prosettings").data("opened",1);this.fixSettingsPosition(!0)},hideSettings:function(){let b=this,a;null==(a=b.initSettings)||a.call(b);b.n("searchsettings").removeClass(b.settAnim.showClass).addClass(b.settAnim.hideClass);
setTimeout(function(){b.n("searchsettings").css(b.settAnim.hideCSS)},b.settAnim.duration);b.n("prosettings").data("opened",0)}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{searchFor:function(b){"undefined"!=typeof b&&this.n("text").val(b);this.n("textAutocomplete").val("");this.search(!1,!1,!1,!0)},toggleSettings:function(b){"undefined"!=typeof b?"show"==b?this.showSettings():this.hideSettings():1==this.n("prosettings").data("opened")?this.hideSettings():this.showSettings()},closeResults:function(b){"undefined"!=typeof b&&b&&(this.n("text").val(""),this.n("textAutocomplete").val(""));this.hideResults();this.n("proloading").css("display",
"none");this.hideLoader();this.searchAbort()},getStateURL:function(){let b=location.href,a;b=b.split("p_asid");b=b[0];b=b.replace("&asl_active=1","");b=b.replace("?asl_active=1","");b="?"==b.slice(-1)?b.slice(0,-1):b;b="&"==b.slice(-1)?b.slice(0,-1):b;a=1<b.indexOf("?")?"&":"?";return b+a+"p_asid="+this.o.id+"&p_asl_data=1&"+c("form",this.n("searchsettings")).serialize()},resetSearch:function(){this.resetSearchFilters()},filtersInitial:function(){return 1==this.n("searchsettings").find("input[name=filters_initial]").val()},
filtersChanged:function(){return 1==this.n("searchsettings").find("input[name=filters_changed]").val()}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.helpers,{Hooks:window.WPD.Hooks,deviceType:function(){let b=window.innerWidth;return 640>=b?"phone":1024>=b?"tablet":"desktop"},detectIOS:function(){return"undefined"!=typeof window.navigator&&"undefined"!=typeof window.navigator.userAgent?null!=window.navigator.userAgent.match(/(iPod|iPhone|iPad)/):!1},detectIE:function(){var b=window.navigator.userAgent;let a=b.indexOf("MSIE ");b=b.indexOf("Trident/");return 0<a||0<b?!0:!1},isMobile:function(){try{return document.createEvent("TouchEvent"),
!0}catch(b){return!1}},isTouchDevice:function(){return"ontouchstart"in window},isSafari:function(){return/^((?!chrome|android).)*safari/i.test(navigator.userAgent)},whichjQuery:function(b){let a=!1;"undefined"!=typeof window.$&&("undefined"===typeof b?a=window.$:"undefined"!=typeof window.$.fn[b]&&(a=window.$));!1===a&&"undefined"!=typeof window.jQuery&&(a=window.jQuery,"undefined"===typeof b?a=window.jQuery:"undefined"!=typeof window.jQuery.fn[b]&&(a=window.jQuery));return a},formData:function(b,
a){let d=this,e=b.find("input,textarea,select,button").get();if(1===arguments.length)return a={},e.forEach(function(f){f.name&&!f.disabled&&(f.checked||/select|textarea/i.test(f.nodeName)||/text/i.test(f.type)||c(f).hasClass("hasDatepicker")||c(f).hasClass("asl_slider_hidden"))&&(void 0==a[f.name]&&(a[f.name]=[]),c(f).hasClass("hasDatepicker")?a[f.name].push(c(f).parent().find(".asl_datepicker_hidden").val()):a[f.name].push(c(f).val()))}),JSON.stringify(a);"object"!=typeof a&&(a=JSON.parse(a));e.forEach(function(f){if(f.name)if(a[f.name]){let g=
a[f.name],h=c(f);"[object Array]"!==Object.prototype.toString.call(g)&&(g=[g]);if("checkbox"==f.type||"radio"==f.type){let k=h.val(),l=!1;for(let m=0;m<g.length;m++)if(g[m]==k){l=!0;break}h.prop("checked",l)}else h.val(g[0]),(c(f).hasClass("asl_gochosen")||c(f).hasClass("asl_goselect2"))&&WPD.intervalUntilExecute(function(k){k(f).trigger("change.asl_select2")},function(){return d.whichjQuery("asl_select2")},50,3),c(f).hasClass("hasDatepicker")&&WPD.intervalUntilExecute(function(k){let l=g[0],m=k(h.get(0)).datepicker("option",
"dateFormat");k(h.get(0)).datepicker("option","dateFormat","yy-mm-dd");k(h.get(0)).datepicker("setDate",l);k(h.get(0)).datepicker("option","dateFormat",m);k(h.get(0)).trigger("selectnochange")},function(){return d.whichjQuery("datepicker")},50,3)}else"checkbox"!=f.type&&"radio"!=f.type||c(f).prop("checked",!1)});return b},submitToUrl:function(b,a,d,e){let f;f=c('<form style="display: none;" />');f.attr("action",b);f.attr("method",a);c("body").append(f);"undefined"!==typeof d&&null!==d&&Object.keys(d).forEach(function(g){let h=
d[g],k=c('<input type="hidden" />');k.attr("name",g);k.attr("value",h);f.append(k)});"undefined"!=typeof e&&"new"==e&&f.attr("target","_blank");f.get(0).submit()},openInNewTab:function(b){Object.assign(document.createElement("a"),{target:"_blank",href:b}).click()},isScrolledToBottom:function(b,a){return b.scrollHeight-b.scrollTop-c(b).outerHeight()<a},getWidthFromCSSValue:function(b,a){b+="";b=-1<b.indexOf("px")?parseInt(b,10):-1<b.indexOf("%")?"undefined"!=typeof a&&null!=a?Math.floor(parseInt(b,
10)/100*a):parseInt(b,10):parseInt(b,10);return 100>b?100:b},nicePhrase:function(b){return encodeURIComponent(b).replace(/%20/g,"+")},unqoutePhrase:function(b){return b.replace(/["']/g,"")},decodeHTMLEntities:function(b){let a=document.createElement("div");b&&"string"===typeof b&&(b=b.replace(/<script[^>]*>([\S\s]*?)<\/script>/gmi,""),b=b.replace(/<\/?\w(?:[^"'>]|"[^"]*"|'[^']*')*>/gmi,""),a.innerHTML=b,b=a.textContent,a.textContent="");return b},isScrolledToRight:function(b){return b.scrollWidth-
c(b).outerWidth()===b.scrollLeft},isScrolledToLeft:function(b){return 0===b.scrollLeft},wp_hooks_apply_filters:function(){return"undefined"!=typeof wp&&"undefined"!=typeof wp.hooks&&"undefined"!=typeof wp.hooks.applyFilters?wp.hooks.applyFilters.apply(null,arguments):"undefined"!=typeof arguments[1]?arguments[1]:!1}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{detectAndFixFixedPositioning:function(){let a=!1,d=this.n("search").get(0);for(;d;)if(d=d.parentElement,null!=d&&"fixed"==window.getComputedStyle(d).position){a=!0;break}a||"fixed"==this.n("search").css("position")?("absolute"==this.n("resultsDiv").css("position")&&this.n("resultsDiv").css({position:"fixed","z-index":2147483647}),this.o.blocking||this.n("searchsettings").css({position:"fixed","z-index":2147483647})):
("fixed"==this.n("resultsDiv").css("position")&&this.n("resultsDiv").css("position","absolute"),this.o.blocking||this.n("searchsettings").css("position","absolute"))},fixResultsPosition:function(a){a="undefined"==typeof a?!1:a;var d=c("body");let e=0;var f=this.n("resultsDiv").css("position");if(0!=c._fn.bodyTransformY()||"static"!=d.css("position"))e=d.offset().top;0!=c._fn.bodyTransformY()&&"fixed"==f&&(f="absolute",this.n("resultsDiv").css("position","absolute"));"fixed"==f&&(e=0);if("fixed"==
f||"absolute"==f)if(1==a||"visible"==this.n("resultsDiv").css("visibility")){a=this.n("search").offset();f=0;if(0!=c._fn.bodyTransformX()||"static"!=d.css("position"))f=d.offset().left;if("undefined"!=typeof a){let g=0;d="phone"==b.deviceType()?this.o.results.width_phone:"tablet"==b.deviceType()?this.o.results.width_tablet:this.o.results.width;"auto"==d&&(d=240>this.n("search").outerWidth()?240:this.n("search").outerWidth());this.n("resultsDiv").css("width",isNaN(d)?d:d+"px");"right"==this.o.resultsSnapTo?
g=this.n("resultsDiv").outerWidth()-this.n("search").outerWidth():"center"==this.o.resultsSnapTo&&(g=Math.floor((this.n("resultsDiv").outerWidth()-parseInt(this.n("search").outerWidth()))/2));this.n("resultsDiv").css({top:a.top+this.n("search").outerHeight(!0)-e+"px",left:a.left-g-f+"px"})}}},fixSettingsPosition:function(a){a="undefined"==typeof a?!1:a;var d=c("body"),e=0,f=this.n("searchsettings").css("position");if(0!=c._fn.bodyTransformY()||"static"!=d.css("position"))e=d.offset().top;0!=c._fn.bodyTransformY()&&
"fixed"==f&&(f="absolute",this.n("searchsettings").css("position","absolute"));"fixed"==f&&(e=0);if(1==a||0!=this.n("prosettings").data("opened")){a=0;if(0!=c._fn.bodyTransformX()||"static"!=d.css("position"))a=d.offset().left;this.fixSettingsWidth();d="none"!=this.n("prosettings").css("display")?this.n("prosettings"):this.n("promagnifier");f=d.offset();e=f.top+d.height()-2-e+"px";d="left"==this.o.settingsimagepos?f.left:f.left+d.width()-this.n("searchsettings").width();d=d-a+"px";this.n("searchsettings").css({display:"block",
top:e,left:d})}},fixSettingsWidth:function(){},hideOnInvisibleBox:function(){if(1==this.o.detectVisibility&&!this.n("search").hasClass("hiddend")&&(this.n("search").is(":hidden")||!this.n("search").is(":visible"))){let a;null==(a=this.hideSettings)||a.call(this);this.hideResults()}}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initAutocompleteEvent:function(){let b=this;1==b.o.autocomplete.enabled&&(b.n("text").on("keyup",function(a){b.keycode=a.keyCode||a.which;b.ktype=a.type;let d=39;c("body").hasClass("rtl")&&(d=37);b.keycode==d&&""!=b.n("textAutocomplete").val()?(a.preventDefault(),b.n("text").val(b.n("textAutocomplete").val()),null!=b.post&&b.post.abort(),b.search()):(null!=b.postAuto&&b.postAuto.abort(),b.autocompleteGoogleOnly())}),b.n("text").on("keyup mouseup input blur select",
function(){b.fixAutocompleteScrollLeft()}))}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initMagnifierEvents:function(){let b=this;b.n("promagnifier").on("click",function(a){b.keycode=a.keyCode||a.which;b.ktype=a.type;let d;null==(d=b.gaEvent)||d.call(b,"magnifier");if(b.n("text").val().length>=b.o.charcount&&1==b.o.redirectOnClick&&"first_result"!=b.o.trigger.click)return b.doRedirectToResults("click"),clearTimeout(void 0),!1;if("ajax_search"!=b.o.trigger.click&&"first_result"!=b.o.trigger.click)return!1;b.searchAbort();clearTimeout(b.timeouts.search);
b.n("proloading").css("display","none");b.timeouts.search=setTimeout(function(){c("form",b.n("searchsettings")).serialize()+b.n("text").val().trim()!=b.lastSuccesfulSearch||!b.resultsOpened&&!b.usingLiveLoader?b.search():b.isRedirectToFirstResult()?b.doRedirectToFirstResult():b.n("proclose").css("display","block")},b.o.trigger.delay)})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initFacetEvents:function(){let b=this;c("input[type=checkbox]",b.n("searchsettings")).on("asl_chbx_change",function(a){b.ktype=a.type;b.n("searchsettings").find("input[name=filters_changed]").val(1);let d;null==(d=b.gaEvent)||d.call(b,"facet_change",{option_label:c(this).closest("fieldset").find("legend").text(),option_value:c(this).closest(".asl_option").find(".asl_option_label").text()+(c(this).prop("checked")?"(checked)":"(unchecked)")});
b.setFilterStateInput(65);b.searchWithCheck(80)})}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initInputEvents:function(){let a=this,d=!1,e=function(){a.n("text").off("mousedown touchstart keydown",e);if(!d){a._initFocusInput();a.o.trigger.type&&a._initSearchInput();a._initEnterEvent();a._initFormEvent();let f;null==(f=a.initAutocompleteEvent)||f.call(a);d=!0}};a.n("text").on("mousedown touchstart keydown",e,{passive:!0})},_initFocusInput:function(){let a=this;a.n("text").on("click",function(d){d.stopPropagation();
d.stopImmediatePropagation();c(this).trigger("focus");let e;null==(e=a.gaEvent)||e.call(a,"focus");if(c("form",a.n("searchsettings")).serialize()+a.n("text").val().trim()==a.lastSuccesfulSearch)return a.resultsOpened||a.usingLiveLoader||(a._no_animations=!0,a.showResults(),a._no_animations=!1),!1});a.n("text").on("focus input",function(d){a.searching||(""!=c(this).val()?a.n("proclose").css("display","block"):a.n("proclose").css({display:"none"}))})},_initSearchInput:function(){let a=this,d=a.n("text").val();
a.n("text").on("input",function(e){a.keycode=e.keyCode||e.which;a.ktype=e.type;if(b.detectIE()){if(d==a.n("text").val())return!1;d=a.n("text").val()}a.updateHref();if(a.n("text").val().length<a.o.charcount){a.n("proloading").css("display","none");if(0==a.o.blocking){let f;null==(f=a.hideSettings)||f.call(a)}a.hideResults(!1);a.searchAbort();clearTimeout(a.timeouts.search);return!1}a.searchAbort();clearTimeout(a.timeouts.search);a.n("proloading").css("display","none");a.timeouts.search=setTimeout(function(){c("form",
a.n("searchsettings")).serialize()+a.n("text").val().trim()!=a.lastSuccesfulSearch||!a.resultsOpened&&!a.usingLiveLoader?a.search():a.isRedirectToFirstResult()?a.doRedirectToFirstResult():a.n("proclose").css("display","block")},a.o.trigger.delay)})},_initEnterEvent:function(){let a=this,d,e=!1;a.n("text").on("keyup",function(f){a.keycode=f.keyCode||f.which;a.ktype=f.type;if(13==a.keycode){clearTimeout(d);d=setTimeout(function(){e=!1},300);if(e)return!1;e=!0}f=c(this).hasClass("orig");if(a.n("text").val().length>=
a.o.charcount&&f&&13==a.keycode){let g;null==(g=a.gaEvent)||g.call(a,"return");1==a.o.redirectOnEnter?"first_result"!=a.o.trigger.return?a.doRedirectToResults(a.ktype):a.search():"ajax_search"==a.o.trigger.return&&(c("form",a.n("searchsettings")).serialize()+a.n("text").val().trim()!=a.lastSuccesfulSearch||!a.resultsOpened&&!a.usingLiveLoader)&&a.search();clearTimeout(a.timeouts.search)}})},_initFormEvent:function(){let a=this;c(a.n("text").closest("form").get(0)).on("submit",function(d,e){d.preventDefault();
b.isMobile()?a.o.redirectOnEnter?(d=new Event("keyup"),d.keyCode=d.which=13,this.n("text").get(0).dispatchEvent(d)):(a.search(),document.activeElement.blur()):"undefined"!=typeof e&&"ajax"==e&&a.search()})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initNavigationEvents:function(){let b=this,a=function(d){let e=d.keyCode||d.which;if(0<c(".item",b.n("resultsDiv")).length&&"none"!=b.n("resultsDiv").css("display")&&"vertical"==b.o.resultstype){if(40==e||38==e){var f=b.n("resultsDiv").find(".item.hovered");b.n("text").trigger("blur");0==f.length?b.n("resultsDiv").find(".item").first().addClass("hovered"):(40==e&&(0==f.next(".item").length?b.n("resultsDiv").find(".item").removeClass("hovered").first().addClass("hovered"):
f.removeClass("hovered").next(".item").addClass("hovered")),38==e&&(0==f.prev(".item").length?b.n("resultsDiv").find(".item").removeClass("hovered").last().addClass("hovered"):f.removeClass("hovered").prev(".item").addClass("hovered")));d.stopPropagation();d.preventDefault();b.n("resultsDiv").find(".resdrg .item.hovered").inViewPort(50,b.n("resultsDiv").get(0))||(f=b.n("resultsDiv").find(".resdrg .item.hovered").get(0),null!=f&&"undefined"!=typeof f.scrollIntoView&&f.scrollIntoView({behavior:"smooth",
block:"start",inline:"nearest"}))}13==e&&0<c(".item.hovered",b.n("resultsDiv")).length&&(d.stopPropagation(),d.preventDefault(),c(".item.hovered a.asl_res_url",b.n("resultsDiv")).get(0).click())}};b.documentEventHandlers.push({node:document,event:"keydown",handler:a});c(document).on("keydown",a)}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initOtherEvents:function(){let a=this;if(b.isMobile()&&b.detectIOS())a.n("text").on("touchstart",function(){a.savedScrollTop=window.scrollY;a.savedContainerTop=a.n("search").offset().top});a.n("proclose").on(a.clickTouchend,function(e){e.preventDefault();e.stopImmediatePropagation();a.n("text").val("");a.n("textAutocomplete").val("");a.hideResults();a.n("text").trigger("focus");a.n("proloading").css("display",
"none");a.hideLoader();a.searchAbort();0<c(".asl_es_"+a.o.id).length?(a.showLoader(),a.liveLoad(".asl_es_"+a.o.id,a.getCurrentLiveURL(),!1)):a.o.resPage.useAjax&&(a.showLoader(),a.liveLoad(a.o.resPage.selector,a.getRedirectURL()));a.n("text").get(0).focus()});if(b.isMobile()){var d=function(){a.orientationChange();setTimeout(function(){a.orientationChange()},600)};a.documentEventHandlers.push({node:window,event:"orientationchange",handler:d});c(window).on("orientationchange",d)}else d=function(){a.resize()},
a.documentEventHandlers.push({node:window,event:"resize",handler:d}),c(window).on("resize",d,{passive:!0});d=function(){a.scrolling(!1)};a.documentEventHandlers.push({node:window,event:"scroll",handler:d});c(window).on("scroll",d,{passive:!0});if(b.isMobile()&&""!=a.o.mobile.menu_selector)c(a.o.mobile.menu_selector).on("touchend",function(){let e=this;setTimeout(function(){let f=c(e).find("input.orig");f=0==f.length?c(e).next().find("input.orig"):f;f=0==f.length?c(e).parent().find("input.orig"):f;
f=0==f.length?a.n("text"):f;a.n("search").inViewPort()&&f.get(0).focus()},300)});b.detectIOS()&&b.isMobile()&&b.isTouchDevice()&&16>parseInt(a.n("text").css("font-size"))&&(a.n("text").data("fontSize",a.n("text").css("font-size")).css("font-size","16px"),a.n("textAutocomplete").css("font-size","16px"),c("body").append("<style>#ajaxsearchlite"+a.o.rid+" input.orig::-webkit-input-placeholder{font-size: 16px !important;}</style>"))},orientationChange:function(){this.detectAndFixFixedPositioning();this.fixSettingsPosition();
this.fixResultsPosition();"isotopic"==this.o.resultstype&&"visible"==this.n("resultsDiv").css("visibility")&&(this.calculateIsotopeRows(),this.showPagination(!0),this.removeAnimation())},resize:function(){this.detectAndFixFixedPositioning();this.fixSettingsPosition();this.fixResultsPosition();"isotopic"==this.o.resultstype&&"visible"==this.n("resultsDiv").css("visibility")&&(this.calculateIsotopeRows(),this.showPagination(!0),this.removeAnimation())},scrolling:function(a){this.detectAndFixFixedPositioning();
this.hideOnInvisibleBox();this.fixSettingsPosition(a);this.fixResultsPosition(a)},initTryThisEvents:function(){let a=this;0<a.n("trythis").find("a").length&&(a.n("trythis").find("a").on("click touchend",function(d){d.preventDefault();d.stopImmediatePropagation();document.activeElement.blur();a.n("textAutocomplete").val("");a.n("text").val(c(this).html());let e;null==(e=a.gaEvent)||e.call(a,"try_this");a.searchWithCheck(80)}),a.n("trythis").css({visibility:"visible"}))}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initResultsEvents:function(){let b=this;b.n("resultsDiv").css({opacity:"0"});let a=function(d){let e=d.keyCode||d.which,f=d.type;0==c(d.target).closest(".asl_w").length&&(b.hideOnInvisibleBox(),"click"==f&&"touchend"==f&&3==e||0==b.resultsOpened||1!=b.o.closeOnDocClick||b.dragging||(b.hideLoader(),b.searchAbort(),b.hideResults()))};b.documentEventHandlers.push({node:document,event:b.clickTouchend,handler:a});c(document).on(b.clickTouchend,
a);b.n("resultsDiv").on("click",".results .item",function(){let d;null==(d=b.gaEvent)||d.call(b,"result_click",{result_title:c(this).find("a.asl_res_url").text(),result_url:c(this).find("a.asl_res_url").attr("href")});1==b.o.singleHighlight&&(localStorage.removeItem("asl_phrase_highlight"),""!=b.n("text").val().replace(/["']/g,"")&&localStorage.setItem("asl_phrase_highlight",JSON.stringify({phrase:b.n("text").val().replace(/["']/g,"")})))})}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initSettingsSwitchEvents:function(){let a=this;a.n("prosettings").on("click",function(){0==a.n("prosettings").data("opened")?a.showSettings():a.hideSettings()});1==a.o.settingsVisible&&a.showSettings(!1)},initSettingsEvents:function(){let a=this,d,e=function(){"undefined"===typeof a.originalFormData&&(a.originalFormData=b.formData(c("form",a.n("searchsettings"))));a.n("searchsettings").off("mousedown touchstart mouseover",
e)};a.n("searchsettings").on("mousedown touchstart mouseover",e);let f=function(g){if(0==c(g.target).closest(".asl_w").length&&!a.dragging){let h;null==(h=a.hideSettings)||h.call(a)}};a.documentEventHandlers.push({node:document,event:a.clickTouchend,handler:f});c(document).on(a.clickTouchend,f);a.n("searchsettings").on("click",function(){a.settingsChanged=!0});a.n("searchsettings").on(a.clickTouchend,function(g){a.updateHref();"undefined"==typeof g.target||c(g.target).hasClass("noUi-handle")?"click"==
g.type&&g.stopImmediatePropagation():g.stopImmediatePropagation()});c('.asl_option_cat input[type="checkbox"]',a.n("searchsettings")).on("asl_chbx_change",function(){a.settingsCheckboxToggle(c(this).closest(".asl_option_cat"))});c(".asl_option_cat",a.n("searchsettings")).forEach(function(g){a.settingsCheckboxToggle(c(g),!1)});c("div.asl_option",a.n("searchsettings")).on(a.mouseupTouchend,function(g){g.preventDefault();g.stopImmediatePropagation();if(a.dragging)return!1;c(this).find('input[type="checkbox"]').prop("checked",
!c(this).find('input[type="checkbox"]').prop("checked"));clearTimeout(d);let h=this;d=setTimeout(function(){c(h).find('input[type="checkbox"]').trigger("asl_chbx_change")},50)});c("div.asl_option label",a.n("searchsettings")).on("click",function(g){g.preventDefault()});c("fieldset.asl_checkboxes_filter_box",a.n("searchsettings")).forEach(function(){let g=!0;c(this).find('.asl_option:not(.asl_option_selectall) input[type="checkbox"]').forEach(function(){if(1==c(this).prop("checked"))return g=!1});
g&&c(this).find('.asl_option_selectall input[type="checkbox"]').prop("checked",!1).removeAttr("data-origvalue")});c("fieldset",a.n("searchsettings")).forEach(function(){c(this).find(".asl_option:not(.hiddend)").last().addClass("asl-o-last")});c('.asl_option_cat input[type="checkbox"], .asl_option_cff input[type="checkbox"]',a.n("searchsettings")).on("asl_chbx_change",function(){let g=c(this).data("targetclass");"string"==typeof g&&""!=g&&c("input."+g,a.n("searchsettings")).prop("checked",c(this).prop("checked"))})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{monitorTouchMove:function(){let b=this;b.dragging=!1;c("body").on("touchmove",function(){b.dragging=!0}).on("touchstart",function(){b.dragging=!1})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initAutop:function(){let b=this;if("disabled"==b.o.autop.state)return!1;let a=window.location.href;if(-1<a.indexOf("asl_ls=")||-1<a.indexOf("asl_ls&"))return!1;let d=b.o.autop.count;window.WPD.intervalUntilExecute(function(){b.isAutoP=!0;"phrase"==b.o.autop.state?(b.o.is_results_page||b.n("text").val(b.o.autop.phrase),b.search(d)):"latest"==b.o.autop.state?b.search(d,1):b.search(d,2)},function(){return!window.ASL.css_async||"undefined"!=typeof window.ASL.css_loaded})}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initEtc:function(){b.Hooks.addFilter("asl/init/etc",this)}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite,a=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{init:function(d,e){this.autopStartedTheSearch=this.isAutoP=this.triggerPrevState=this.searching=!1;this.autopData={};this.resultsOpened=this.settingsChanged=this.resultsInitialized=this.settingsInitialized=!1;this.postAuto=this.post=null;this.scroll={};this.savedContainerTop=this.savedScrollTop=0;this.disableMobileScroll=!1;this.clickTouchend="click touchend";this.mouseupTouchend=
"mouseup touchend";this.noUiSliders=[];this.timeouts={compactBeforeOpen:null,compactAfterOpen:null,search:null,searchWithCheck:null};this.eh={};this.documentEventHandlers=[];this.settScroll=null;this.currentPage=1;this.sIsotope=this.isotopic=null;this.lastSuccesfulSearch="";this.lastSearchData={};this._no_animations=!1;this.results_num=this.call_num=0;this.o=c.fn.extend({},d);this.nodes={};this.nodes.search=c(e);a.isMobile()?this.animOptions=this.o.animations.mob:this.animOptions=this.o.animations.pc;
this.initNodeVariables();this.animationOpacity=0>this.animOptions.items.indexOf("In")?"opacityOne":"opacityZero";this.o.redirectOnClick="ajax_search"!=this.o.trigger.click&&"nothing"!=this.o.trigger.click;this.o.redirectOnEnter="ajax_search"!=this.o.trigger.return&&"nothing"!=this.o.trigger.return;if(this.usingLiveLoader=this.o.resPage.useAjax&&0<c(this.o.resPage.selector).length||0<c(".asl_es_"+this.o.id).length)this.o.trigger.type=this.o.resPage.trigger_type,this.o.trigger.facet=this.o.resPage.trigger_facet,
this.o.resPage.trigger_magnifier&&(this.o.redirectOnClick=0,this.o.trigger.click="ajax_search"),this.o.resPage.trigger_return&&(this.o.redirectOnEnter=0,this.o.trigger.return="ajax_search");this.monitorTouchMove();this.initEvents();this.initAutop();this.initEtc();b.firstIteration=!1;this.n("s").trigger("asl_init_search_bar",[this.o.id,this.o.iid],!0,!0);return this},n:function(d){if("undefined"===typeof this.nodes[d])switch(d){case "s":this.nodes[d]=this.nodes.search;break;case "container":this.nodes[d]=
this.nodes.search.closest(".asl_w_container");break;case "searchsettings":this.nodes[d]=c(".asl_s",this.n("container"));break;case "resultsDiv":this.nodes[d]=c(".asl_r",this.n("container"));break;case "probox":this.nodes[d]=c(".probox",this.nodes.search);break;case "proinput":this.nodes[d]=c(".proinput",this.nodes.search);break;case "text":this.nodes[d]=c(".proinput input.orig",this.nodes.search);break;case "textAutocomplete":this.nodes[d]=c(".proinput input.autocomplete",this.nodes.search);break;
case "proloading":this.nodes[d]=c(".proloading",this.nodes.search);break;case "proclose":this.nodes[d]=c(".proclose",this.nodes.search);break;case "promagnifier":this.nodes[d]=c(".promagnifier",this.nodes.search);break;case "prosettings":this.nodes[d]=c(".prosettings",this.nodes.search);break;case "settingsAppend":this.nodes[d]=c("#wpdreams_asl_settings_"+this.o.id);break;case "resultsAppend":this.nodes[d]=c("#wpdreams_asl_results_"+this.o.id);break;case "trythis":this.nodes[d]=c("#asp-try-"+this.o.rid);
break;case "hiddenContainer":this.nodes[d]=c(".asl_hidden_data",this.n("container"));break;case "aspItemOverlay":this.nodes[d]=c(".asl_item_overlay",this.n("hiddenContainer"));break;case "showmore":this.nodes[d]=c(".showmore",this.n("resultsDiv"));break;case "items":this.nodes[d]=0<c(".item",this.n("resultsDiv")).length?c(".item",this.n("resultsDiv")):c(".photostack-flip",this.n("resultsDiv"));break;case "results":this.nodes[d]=c(".results",this.n("resultsDiv"));break;case "resdrg":this.nodes[d]=
c(".resdrg",this.n("resultsDiv"))}return this.nodes[d]},initNodeVariables:function(){this.o.id=this.nodes.search.data("id");this.o.iid=this.nodes.search.data("instance");this.o.rid=this.o.id+"_"+this.o.iid;this.fixClonedSelf()},initEvents:function(){let d;null==(d=this.initSettingsSwitchEvents)||d.call(this);this.initOtherEvents();this.initMagnifierEvents();this.initInputEvents()}})})(WPD.dom);
(function(c){let b=window.WPD.ajaxsearchlite.helpers;c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initResults:function(){if(!this.resultsInitialized){this.initResultsBox();this.initResultsEvents();let a;null==(a=this.initNavigationEvents)||a.call(this)}},initResultsBox:function(){this.initResultsAnimations();b.isMobile()&&1==this.o.mobile.force_res_hover?(this.o.resultsposition="hover",this.nodes.resultsDiv=this.n("resultsDiv").clone(),c("body").append(this.nodes.resultsDiv),this.nodes.resultsDiv.css({position:"absolute"}),
this.detectAndFixFixedPositioning()):"hover"==this.o.resultsposition&&0>=this.n("resultsAppend").length?(this.nodes.resultsDiv=this.n("resultsDiv").clone(),c("body").append(this.n("resultsDiv"))):(this.o.resultsposition="block",this.n("resultsDiv").css({position:"static"}),0<this.n("resultsAppend").length&&(0<this.n("resultsAppend").find(".asl_w").length?this.nodes.resultsDiv=this.n("resultsAppend").find(".asl_w"):(this.nodes.resultsDiv=this.n("resultsDiv").clone(),this.nodes.resultsAppend.append(this.n("resultsDiv")))));
this.nodes.showmore=c(".showmore",this.n("resultsDiv"));this.nodes.items=0<c(".item",this.n("resultsDiv")).length?c(".item",this.n("resultsDiv")):c(".photostack-flip",this.n("resultsDiv"));this.nodes.results=c(".results",this.n("resultsDiv"));this.nodes.resdrg=c(".resdrg",this.n("resultsDiv"));this.n("resultsDiv").get(0).id=this.n("resultsDiv").get(0).id.replace("__original__","");this.detectAndFixFixedPositioning();this.resultsInitialized=!0},initResultsAnimations:function(){this.resAnim={showClass:"asl_an_fadeInDrop",
showCSS:{visibility:"visible",display:"block",opacity:1,"animation-duration":"300ms"},hideClass:"asl_an_fadeOutDrop",hideCSS:{visibility:"hidden",opacity:0,display:"none"},duration:300};this.n("resultsDiv").css({"-webkit-animation-duration":"300ms","animation-duration":"300ms"})}})})(WPD.dom);
(function(c){c.fn.extend(window.WPD.ajaxsearchlite.plugin,{initSettings:function(){if(!this.settingsInitialized){let b;null==(b=this.loadASLFonts)||b.call(this);let a;null==(a=this.initSettingsBox)||a.call(this);let d;null==(d=this.initSettingsEvents)||d.call(this);let e;null==(e=this.initFacetEvents)||e.call(this)}},initSettingsBox:function(){let b=this,a;null==(a=b.initSettingsAnimations)||a.call(b);(function(d){let e=b.n("searchsettings").get(0);b.nodes.searchsettings=b.n("searchsettings").clone();
d.append(b.n("searchsettings"));c(e).find("*[id]").forEach(function(f){0>f.id.indexOf("__original__")&&(f.id="__original__"+f.id)});b.n("searchsettings").find("*[id]").forEach(function(f){-1<f.id.indexOf("__original__")&&(f.id=f.id.replace("__original__",""))})})(c("body"));b.n("searchsettings").get(0).id=b.n("searchsettings").get(0).id.replace("__original__","");b.detectAndFixFixedPositioning();b.settingsInitialized=!0},initSettingsAnimations:function(){this.settAnim={showClass:"",showCSS:{visibility:"visible",
display:"block",opacity:1,"animation-duration":this.animOptions.settings.dur+"ms"},hideClass:"",hideCSS:{visibility:"hidden",opacity:0,display:"none"},duration:this.animOptions.settings.dur+"ms"};"fade"==this.animOptions.settings.anim&&(this.settAnim.showClass="asl_an_fadeIn",this.settAnim.hideClass="asl_an_fadeOut");"fadedrop"!=this.animOptions.settings.anim||this.o.blocking?"fadedrop"==this.animOptions.settings.anim&&(this.settAnim.showClass="asl_an_fadeIn",this.settAnim.hideClass="asl_an_fadeOut"):
(this.settAnim.showClass="asl_an_fadeInDrop",this.settAnim.hideClass="asl_an_fadeOutDrop");this.n("searchsettings").css({"-webkit-animation-duration":this.settAnim.duration+"ms","animation-duration":this.settAnim.duration+"ms"})}})})(WPD.dom);window.ASL="undefined"!==typeof window.ASL?window.ASL:{};
window.ASL.api=function(){let c=function(d,e,f,g){d=ASL.instances.get(d,e);return!1!==d&&d[f].apply(d,[g])},b=function(d,e,f){if(!isNaN(parseFloat(e))&&isFinite(e))return d=ASL.instances.get(d,e),!1!==d&&d[f].apply(d);d=ASL.instances.get(d);return!1!==d&&d.forEach(function(g){g[e].apply(g,[f])})},a=function(d,e){if("exists"==e)return ASL.instances.exist(d);d=ASL.instances.get(d);return!1!==d&&d.forEach(function(f){f[e].apply(f)})};if(4==arguments.length)return c.apply(this,arguments);if(3==arguments.length)return b.apply(this,
arguments);if(2==arguments.length)return a.apply(this,arguments);0==arguments.length&&(console.log("Usage: ASL.api(id, [optional]instance, function, [optional]args);"),console.log("For more info: https://knowledgebase.ajaxsearchlite.com/other/javascript-api"))};
window._ASL_load=function(){let c=WPD.dom;window.ASL.instances={instances:[],get:function(b,a){this.clean();if("undefined"===typeof b||0==b)return this.instances;if("undefined"===typeof a){a=[];for(var d=0;d<this.instances.length;d++)this.instances[d].o.id==b&&a.push(this.instances[d]);return 0<a.length?a:!1}for(d=0;d<this.instances.length;d++)if(this.instances[d].o.id==b&&this.instances[d].o.iid==a)return this.instances[d];return!1},set:function(b){if(this.exist(b.o.id,b.o.iid))return!1;this.instances.push(b);
return!0},exist:function(b,a){this.clean();for(let d=0;d<this.instances.length;d++)if(this.instances[d].o.id==b&&("undefined"===typeof a||this.instances[d].o.iid==a))return!0;return!1},clean:function(){let b=[],a=this;this.instances.forEach(function(d,e){0==c(".asl_m_"+d.o.rid).length&&b.push(e)});b.forEach(function(d){"undefined"!==typeof a.instances[d]&&(a.instances[d].destroy(),a.instances.splice(d,1))})},destroy:function(b,a){let d=this.get(b,a);if(!1!==d)if(Array.isArray(d))d.forEach(function(e){e.destroy()}),
this.instances=[];else{let e=0;this.instances.forEach(function(f,g){f.o.id==b&&f.o.iid==a&&(e=g)});d.destroy();this.instances.splice(e,1)}}};window.ASL.initialized=!1;window.ASL.initializeSearchByID=function(b){let a=ASL.getInstances();if("undefined"!==typeof b&&"object"!=typeof b)if("undefined"!==typeof a[b]){let e=[];e[b]=a[b];a=e}else return!1;let d=0;a.forEach(function(e,f){c(".asl_w_container_"+f).forEach(function(g){var h=c(g).parent();h.is("a")&&(g=document.createElement("div"),h=h.get(0),
g.innerHTML=h.innerHTML,h.replaceWith(g))});c(".asl_m_"+f).forEach(function(g){let h=c(g);if("undefined"!=typeof h.get(0).hasAsl)return++d,!0;g.hasAsl=!0;++d;return h.ajaxsearchlite(e)})})};window.ASL.getInstances=function(){if("undefined"!==typeof window.ASL_INSTANCES)return window.ASL_INSTANCES;let b=[];c(".asl_init_data").forEach(function(a){if("undefined"===typeof a.dataset.asldata)return!0;let d=WPD.Base64.decode(a.dataset.asldata);if("undefined"===typeof d||""==d)return!0;b[a.dataset.aslId]=
JSON.parse(d)});return b};window.ASL.initialize=function(b){if("undefined"==typeof ASL.version)return!1;if(window.IntersectionObserver)if(ASL.script_async_load||ASL.init_only_in_viewport){if(b=document.querySelectorAll(".asl_w_container"),b.length){let a=new IntersectionObserver(function(d){d.forEach(function(e){e.isIntersecting&&(ASL.initializeSearchByID(e.target.dataset.id),a.unobserve(e.target))})});b.forEach(function(d){a.observe(d)})}}else ASL.initializeSearchByID(b);else ASL.initializeSearchByID(b);
ASL.initializeMutateDetector();ASL.initializeHighlight();ASL.initializeOtherEvents();ASL.initialized=!0};window.ASL.initializeHighlight=function(){if(this.highlight.enabled){let b=localStorage.getItem("asl_phrase_highlight");localStorage.removeItem("asl_phrase_highlight");null!=b&&(b=JSON.parse(b),this.highlight.data.forEach(function(a){var d=""!=a.selector&&0<c(a.selector).length?a.selector:"article";d=0<c(d).length?d:"body";c(d).highlight(b.phrase,{element:"span",className:"asl_single_highlighted",
wordsOnly:a.whole,excludeParents:".asl_w, .asl-try"});d=c(".asl_single_highlighted");if(a.scroll&&0<d.length){d=d.offset().top-120;let e=c("#wpadminbar");0<e.length&&(d-=e.height());d+=a.scroll_offset;d=0>d?0:d;c("html").animate({scrollTop:d},500)}return!1}))}};window.ASL.initializeOtherEvents=function(){let b,a=this;c("body").on("click touchend","#menu-item-search, .fa-search, .fa, .fas, .fusion-flyout-menu-toggle, .fusion-main-menu-search-open, #search_button, .mini-search.popup-search, .icon-search, .menu-item-search-dropdown, .mobile-menu-button, .td-icon-search, .tdb-search-icon, .side_menu_button, .search_button, .raven-search-form-toggle, [data-elementor-open-lightbox], .elementor-button-link, .elementor-button, i[class*=-search], a[class*=-search]",
function(){clearTimeout(b);b=setTimeout(function(){a.initializeSearchByID()},300)});if("undefined"!=typeof jQuery)jQuery(document).on("elementor/popup/show",function(){setTimeout(function(){a.initializeSearchByID()},10)})};window.ASL.initializeMutateDetector=function(){let b;"undefined"!=typeof ASL.detect_ajax&&1==ASL.detect_ajax&&(new MutationObserver(function(){clearTimeout(b);b=setTimeout(function(){ASL.initializeSearchByID()},500)})).observe(document.querySelector("body"),{subtree:!0,childList:!0})};
window.ASL.ready=function(){if("complete"===document.readyState||"loaded"===document.readyState||"interactive"===document.readyState)this.initialize();else c(document).on("DOMContentLoaded",this.initialize)};window.ASL.loadScriptStack=function(b){let a;0<b.length&&(a=document.createElement("script"),a.src=b.shift().src,a.onload=function(){0<b.length?window.ASL.loadScriptStack(b):window.ASL.ready()},document.body.appendChild(a))};window.ASL.init=function(){ASL.script_async_load?window.ASL.loadScriptStack(ASL.additional_scripts):
"undefined"!==typeof WPD.ajaxsearchlite&&window.ASL.ready()};window.WPD.intervalUntilExecute(window.ASL.init,function(){return"undefined"!=typeof window.ASL.version&&"undefined"!=c.fn.ajaxsearchlite})};(function(){"undefined"!=typeof WPD&&"undefined"!=typeof WPD.dom?window._ASL_load():document.addEventListener("wpd-dom-core-loaded",window._ASL_load)})();
